name: Build & Publish Package to NPM Registry
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to publish'
        required: true
        type: string
jobs:
  publish:
    name: Build and Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.release_tag }}'
      - name : Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Get release information
        id: release_info
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ github.event.inputs.release_tag }}'
            });
            return release.data;
      - name : Running NPM CI
        run: npm ci
      - name : Creating Build
        run: npm run build
      - name : Creating .npmrc file
        run: |
          echo 'save-exact=true' > build/.npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > build/.npmrc
      - name: Determine npm tag
        id: npm_tag
        run: |
          if [[ "${{ github.event.inputs.release_tag }}" == *"alpha"* ]]; then
            echo "tag=alpha" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.release_tag }}" == *"beta"* ]]; then
            echo "tag=beta" >> $GITHUB_ENV
          else
            echo "tag=latest" >> $GITHUB_ENV
          fi
      - name : Publishing Build to NPM
        id : npm_publish
        run: npm publish --tag ${{ env.tag }}
        working-directory: ./build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Check Publish Status
        if: steps.npm_publish.outcome == 'failure'
        run: echo "npm publish failed with exit code ${{ steps.npm_publish.exitCode }}"
      - name: Get Publish Status
        if: steps.npm_publish.outcome == 'success'
        run: echo "npm publish successful"