name: Build & Publish Package to NPM Registry
on:
  release:
    types: [created]
jobs:
  publish:
    name: Build and Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name : Checkout
        uses: actions/checkout@v4
      - name : Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name : Running NPM CI
        run: npm ci
      - name : Creating Build
        run: npm run build
      - name : Creating .npmrc file
        run: |
          echo 'save-exact=true' > build/.npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > build/.npmrc
      - name : Publishing Build to NPM
        id : npm_publish
        run: npm publish --tag alpha
        working-directory: ./build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Check Publish Status
        if: steps.npm_publish.outcome == 'failure'
        run: echo "npm publish failed with exit code ${{ steps.npm_publish.exitCode }}"
      - name: Get Publish Status
        if: steps.npm_publish.outcome == 'success'
        run: echo "npm publish successful"